### PR TITLE
feat: Add support for STM32C0 chips

### PR DESCRIPTION
**Pull request by doceme**
Add support for STM32C011xx and STM32C031xx chips

### CODE REVIEW

**Comment by florisla** [comment]
Thanks!

If you're up to it, it would be great if you could test the 'device-table' branch against some STM32C0 devices.

https://github.com/florisla/stm32loader/tree/feat/device-table

It's supposed to no longer need the `--family` flag, and support all known STM32 devices.

**Comment by florisla** [comment]
See #76 for the pip command to easily install the device-table branch.

**Comment by doceme** [comment]
Yes, I will try to do that soon. Thanks for the suggestion.

**Comment by doceme** [comment]
I was successful in testing this change on the `feat/device-table` branch and was able to remove the `--family` flag without any issues.

**Comment by doceme** [comment]
Sorry, I misunderstood what you meant before. I just realized that you were saying the `feat/device-table` branch should support all known STM32 devices (including the STM32C0 family) without needing this change. I just back out my commit and re-tested. I can confirm the `feat/device-table` branch was able to successfully detect my STM32C0 device and flash it without this PR.

**Comment by florisla** [comment]
Thanks for testing! The next release will be based on the device-table branch so it seems no change is necessary.

**Pull request closed without merging**
