### PR TITLE
Add support for STM32F7 processors

### PR DESCRIPTION
**Pull request by sam-bristow**

### CODE REVIEW

**Comment by florisla** [comment]
This is merged now; would you like to see this soon in a release on PyPI, or are you fine using the git version?

**Comment by sam-bristow** [comment]
I'm fine using it from got for now. Just thought I may as well get the
changes upstream before I moved on and forgot. :-)

I'm also working on a few changes to make things nicer to use as a library
rather than a CLI tool. Is that something you'd be interested in pulling in
to your version? Or out of scope?

**Comment by florisla** [comment]
Very interested to include that, yes.

There are some forks around which would not be necessary if the internal structure was a bit nicer.

I'm not sure how I feel about splitting up into multiple files though.  I think there are many users who just download `stm32loader.py` and execute that directly, without installation via `pip`.

**Comment by florisla** [comment]
@sam-bristow Do you have something available to improve stm32loader as a library?

I'm looking at a use case to program an STM32 over I2C.

In the end I think I'm ready to move off of having everything in one file.
We can leave the current version in a dedicated branch for people who require less features and want a single file.

**Comment by sam-bristow** [comment]
I made a bit of progress but had to move on to other tasks before it was in a usable state.
I do still plan on having another crack but I'm not sure when I'll get a chance unfortunately.

**Comment by florisla** [comment]
Can you share some of your design goals?  What would stm32loader offer when used as a library?

I can work towards them when doing my changes (if/when I get round to it).

**Pull request merged**
